#!/usr/bin/env sh
printenv
export LIBRDKAFKA_VERSION=1.2.1
export EXT_RDKAFKA_VERSION=4.0.0
export DOCKER_REPO=index.docker.io/nickzurich/php-rdkafka
docker build --build-arg LIBRDKAFKA_VERSION=$LIBRDKAFKA_VERSION --build-arg EXT_RDKAFKA_VERSION=$EXT_RDKAFKA_VERSION -t $IMAGE_NAME .
